---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: sdk-key-test-flag

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
